# Basic
title: Roc's Blog
subtitle: 求索
welcome_message: Hi
creator: <a href="http://yuxiaopeng.com">@yuxiaopeng</a>

url: "http://yuxiaopeng.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    #- {title: 项目, description: 我的项目, url: ''}
    #- {title: 关于, description: 了解更多关于我, url: ''}
    #- {title: 订阅, description: 邮件订阅本站, url: ''}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    duoshuo: yuxiaopeng
# Social
social:
    weibo: rooc
    github: yuxiaopeng
    twitter: xiaopengyu
    mail: uxiaopeng@gmail.com

# Google Analytics
ga:
    id: UA-45732020-1
    host: yuxiaopeng.com
